<div>Liste des utilisateurs:

<?php 

if (!empty($users)) {
?>
<table>
    <thead>
        <tr>
            <th>Utilisateur</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
<?php
    foreach ($users as $user) {
?>
        <tr>
            <td><?= $user->getUsername() ?></td>
            <td><?= $user->getNom() ?></td>
            <td><?= $user->getPrenom() ?></td>
            <td><?= $user->getEmail() ?></td>
        </tr>
<?php
    }
?>
    </tbody>
</table>
<?php
}
?>

</div>

<a href="index.php?page=additem">Ajouter des objets</a>
<a href="index.php?page=gestionitem">Gérer les objets</a>
<a href="index.php?page=messagerie">Messagerie</a>
