<div id="add-item-form-wrapper">
    <h1 id="additem-title">Formulaire d'ajout d'objets</h1>
    <?php echo $successMessage; ?>
    <form id="add-item-form" method="POST" enctype="multipart/form-data">
        <label for="add-categorie">Catégorie</label>
        <select name="categorie" id="add-categorie">
        <option value="" disabled>Selectionnez une catégorie</option>
        <option value="bagues">Bagues</option>
        <option value="bracelets">Bracelets</option>
        <option value="colliers">Colliers</option>
        <option value="earrings">Boucles d'oreilles</option>
        <option value="autre">Autre</option>
        </select>
      
        <label for="add-nom">Titre/Nom de l'objet</label><input type="text" name="nom" id="add-nom"/>
        <label for="add-description">Description</label><input type="textarea" name="description" id="add-description"/>
        <label for="add-prix">Prix</label><input type="number" name="prix" id="add-prix"/>
        <label for="add-image">Fichier image</label><input type="file" name="image" id="add-image"/>
        <button name="add" id="additemform-button">Ajouter</button>
    </form>
    
    <a href="index.php?page=administration" class="admin-redirect">Retour à la page d'administration</a>
</div>