<div id="cgu-wrapper">
    <h1>Conditions Générales d'Utilisation du site Symbolique Paris</h1>
    
    <p>Date d'entrée en vigueur : 15 Août 2023</P>
    <p>Bienvenue sur le site web "Symbolique Paris" (ci-après dénommé "le Site"). Les présentes Conditions Générales d'Utilisation (ci-après dénommées "CGU") régissent votre utilisation du Site. Veuillez lire attentivement les CGU avant de naviguer sur le Site, de vous inscrire ou de vous connecter en tant qu'utilisateur.</p>
    
    <h2>1. Acceptation des CGU</h2>
    <p>En utilisant le Site, vous acceptez sans réserve les présentes CGU. Si vous n'êtes pas d'accord avec l'une des dispositions des CGU, veuillez cesser immédiatement d'utiliser le Site.</p>
    
    <h2>2. Inscription et Compte Utilisateur</h2>
    <p>2.1. Pour accéder à certaines fonctionnalités du Site, vous pouvez choisir de vous inscrire en fournissant les informations suivantes : nom, prénom, adresse e-mail, nom d'utilisateur, et mot de passe. Vous êtes responsable de maintenir la confidentialité de votre nom d'utilisateur et de votre mot de passe, et vous acceptez de ne pas partager ces informations avec des tiers.</p>
    <p>2.2. Vous acceptez également de fournir des informations exactes, complètes et à jour lors de votre inscription sur le Site. Symbolique Paris se réserve le droit de suspendre ou de résilier votre compte en cas de non-respect de cette obligation.</p>
    
    <h2>3. Confidentialité et Sécurité des Données</h2>
    <p>3.1. Vos informations personnelles, y compris votre nom, prénom et adresse e-mail, seront traitées conformément au règlement général sur la protection des données (RGPD) et aux lois en vigueur en matière de protection des données. Veuillez consulter notre Politique de Confidentialité pour plus d'informations sur la manière dont nous traitons vos données.</p>
    <p>3.2. Votre mot de passe sera stocké de manière sécurisée, sous forme hachée, ce qui signifie que même l'administrateur du site n'a pas accès à votre mot de passe en clair.</p>
    
    <h2>4. Utilisation du Site</h2>
    <p>4.1. Vous vous engagez à utiliser le Site conformément aux lois en vigueur et aux présentes CGU.</p>
    <p>4.2. Vous acceptez de ne pas utiliser le Site à des fins illégales, offensantes, diffamatoires, ou nuisibles pour Symbolique Paris ou d'autres utilisateurs du Site.</p>
    
    <h2>5. Propriété Intellectuelle</h2>
    <p>5.1. Tous les contenus présents sur le Site, y compris mais sans s'y limiter, les images, les textes, les logos et les designs, sont la propriété de Symbolique Paris et sont protégés par les lois sur la propriété intellectuelle.</p>
    <p>5.2. Vous acceptez de ne pas copier, reproduire, distribuer ou utiliser de quelque manière que ce soit le contenu du Site sans l'autorisation préalable de Symbolique Paris.</p>
    
    <h2>6. Résiliation</h2>
    <p>Symbolique Paris se réserve le droit de résilier ou de suspendre votre compte utilisateur à tout moment, sans préavis, en cas de non-respect des CGU ou pour toute autre raison.</p>
    
    <h2>7. Modifications des CGU</h2>
    <p>Symbolique Paris se réserve le droit de modifier les CGU à tout moment. Les modifications seront publiées sur le Site et prendront effet dès leur publication. Il vous incombe de vérifier régulièrement les CGU pour vous tenir informé des changements.</p>
    
    <h2>8. Contact</h2>
    <p>Pour toute question ou préoccupation concernant les CGU, la sécurité des données ou votre utilisation du Site, veuillez nous contacter à l'adresse suivante : symbolique_paris@yahoo.com.</p>
    <p>En utilisant le Site, vous acceptez d'être lié par ces CGU. Symbolique Paris vous remercie de votre confiance et vous souhaite une agréable expérience sur notre site.</p>
</div>