<h4>Pour nous contacter</h4>

<div>
    <p>Par téléphone</p>
    <p>06.23.26.02.51</p>
</div>

<div>
    <p>Par email</p>
    <p>kauslaurent@yahoo.fr</p>
</div>


<?php if (isset($_SESSION['ID'])) { ?>

<h5>Contactez-nous directement via ce formulaire</h5>
<form method="POST">
    <input type="textarea" name="messageForm"/>
    <button name="sendMessage">Envoyer</button>
</form>

<?php } else { ?>

<p>Vous avez eu un coup de coeur ?<br>
Connectez vous pour nous contacter immédiatement !</p>
<a href="index.php?page=connexion">Se connecter</a>

<p>Pas de compte? Inscrivez-vous !</p>
<a href="index.php?page=inscription">S'inscrire</a>

<?php } ?>
