<h4>Pour nous contacter</h4>

<div>
    <p>Par téléphone</p>
    <p>06.23.26.02.51</p>
</div>

<div>
    <p>Par email</p>
    <p>kauslaurent@yahoo.fr</p>
</div>

<!--Pour les utilisateur NON connectés-->
<p>Vous avez eu un coup de coeur ?<br>
Connectez vous pour nous contacter immédiatement !</p>
<a href="index.php?page=connexion">Se connecter</a>

<p>Pas de compte? Inscrivez-vous !</p>
 <a href="index.php?page=inscription">S'inscrire</a>