<form method="POST">
    
    <select name="categorie">
        <option value="bagues" <?php if ($item->getCategorie()==="bagues") { echo "selected"; } ?>>Bagues</option>
        <option value="bracelets" <?php if ($item->getCategorie()==="bracelets") { echo "selected"; } ?>>Bracelets</option>
        <option value="colliers" <?php if ($item->getCategorie()==="colliers") { echo "selected"; } ?>>Colliers</option>
        <option value="earrings" <?php if ($item->getCategorie()==="earrings") { echo "selected"; } ?>>Boucles d'oreilles</option>
        <option value="autre" <?php if ($item->getCategorie()==="autre") { echo "selected"; } ?>>Autre</option>
    </select><br>
    
    <label for="editNom"><input type="text" name="nom" value="<?= $item->getNom() ?>"><br>
    <label for="editDescription"><input type="text" name="description" value="<?= $item->getDescription() ?>"><br>
    <label for="editPrix"><input type="number" name="prix" value="<?= $item->getPrix() ?>"/><br>
    <label for="editImage"><input type="text" name="image" value="<?= $item->getImage() ?>"><br>
    <button type="submit" name="modifier">Modifier</button><br>
</form>