<div id="gestionitem-wrapper">
    
    <h1>Gestion Administrative</h1>
    
    <span>Liste des objets actuellement en vente:</span>
    
    <?php 
    if (!empty($items)) {
    ?>
    <div id="tableitems-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Catégorie</th>
                    <th>Nom/Titre</th>
                    <th>Description</th>
                    <th>Prix</th>
                    <th>Image</th>
                    <th>Modifier/Supprimer</th>
                </tr>
            </thead>
            <tbody>
        <?php
            foreach ($items as $item) {
        ?>
                <tr>
                    <td><?= $item->getCategorie() ?></td>
                    <td><?= $item->getNom() ?></td>
                    <td><?= $item->getDescription() ?></td>
                    <td><?= $item->getPrix() ?></td>
                    <td><img src="<?= $item->getImage() ?>" alt="<?= $item->getNom() ?>"></td>
                    <td>
                        <form method="POST">
                            <button name="modifItem" id="edit-item" value="<?= $item->getId() ?>">Modifier</button>
                        </form>
                        <form method="POST" class="form-delete">
                            <button name="supprItem" id="delete-item" value="<?= $item->getId() ?>">Supprimer</button>                
                        </form>
                    </td>
                    
                </tr>
        <?php
            }
        ?>
            </tbody>
        </table>
    </div>
    <?php
    }
    ?>
    
</div>

<a class="admin-redirect" href="index.php?page=administration">Retour page administration</a>