<main>
    <img src="#" alt="Photo de [l'intérieur de] la boutique"></img>
    <p>Pour les férus de bijoux vintages et d'objets d'arts ancients ou moderne, tant artisanaux qu'industriels, venez trouver votre bonheur chez Symbolique Paris</p>
    
    <div id="white_square"></div>
    <div id="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2625.4412698565607!2d2.3733829810323583!3d48.849795307969984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6720f5a4be503%3A0xadf5229b9a7bdf7a!2sSymbolique!5e0!3m2!1sfr!2sfr!4v1691065737683!5m2!1sfr!2sfr" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
</main>