<form id="inscriptionForm" method="POST">
    <label for="inscriNom">Entrez votre nom </label><input type="text" name="nom" id="inscriNom"/><br>
    <label for="inscriPrenom">Entrez votre prénom </label><input type="text" name="prenom" id="inscriPrenom"/><br>
    <label for="inscriEmail">Entrez votre email </label><input type="email" name="email" id="inscriEmail"/><br>
    <label for="inscriUsername">Choisissez un nom d'utilisateur </label><input type="text" name="username" id="inscriUsername"/><br>
    <label for="inscriPassword">Choisissez un mot de passe </label><input type="password" name="password" id="inscriPassword"/><br>
    <label for="inscriPassword2">Entrez de nouveau le mot de passe </label><input type="password" name="password2" id="inscriPassword2" /><br>
    <button name="inscription">S'inscrire</button>
</form>