<form method="POST">
    <hold>Entrez votre nom</hold><input type="text" name="nom"/><br>
    <hold>Entrez votre prénom</hold><input type="text" name="prenom"/><br>
    <hold>Choisissez un nom d'utilisateur</hold><input type="text" name="username"/><br>
    <hold>Choisissez un mot de passe</hold><input type="password" name="password"/><br>
    <hold>Entrez de nouveau le mot de passe</hold><input type="password" name="password2"/><br>
    <button name="inscription">S'inscrire</button>
</form>