<h1>Inscription</h1>

<form id="inscriptionForm" method="POST">
    <label for="inscriNom">Nom </label><input type="text" name="nom" id="inscriNom"/><br>
    <label for="inscriPrenom">Prénom </label><input type="text" name="prenom" id="inscriPrenom"/><br>
    <label for="inscriEmail">Email </label><input type="email" name="email" id="inscriEmail"/><br>
    <label for="inscriUsername">Choisissez un nom d'utilisateur </label><input type="text" name="username" id="inscriUsername"/><br>
    <label for="inscriPassword">Choisissez un mot de passe </label><input type="password" name="password" id="inscriPassword"/><br>
    <label for="inscriPassword2">Confirmez le mot de passe </label><input type="password" name="password2" id="inscriPassword2" /><br>
    <button name="inscription">S'inscrire</button>
</form>

<p>Vous possédez déjà un compte ? Connectez-vous !</p>
<a href="index.php?page=connexion">Connexion</a>