<div id="ml-wrapper">    
    <h1>Mentions Légales de Symbolique Paris</h1>
    
    <h2>Propriétaire du Site :</h2>
    <div class="ml-infos">
        <p>Nom: Symbolique Paris</p>
        <p>Adresse: 16 rue de Cotte, 75012, PARIS</p>
        <p>Téléphone: 06.23.26.02.51</p>
        <p>eMail: symbolique_paris@yahoo.com</p>
        <p>N° de Siret: 90793774200019</p>
    </div>
    
    
    <h2>Hébergeur du Site :</h2>
    <div class="ml-infos">
        <p>[Nom de l'hébergeur]</p>
        <p>[Adresse de l'hébergeur]</p>
        <p>[Numéro de téléphone de l'hébergeur]</p>
        <p>[Adresse e-mail de l'hébergeur]</p>
    </div>
    
    <h2>Conditions Générales d'Utilisation :</h2>
    <p>L'utilisation du site web "Symbolique Paris" est soumise aux Conditions Générales d'Utilisation (CGU) consultables à l'adresse <a href="index.php?page=cgu">Politique de Confidentialité</a>.</p>
    
    <h2>Protection des Données Personnelles :</h2>
    <p>Symbolique Paris collecte et traite les données personnelles conformément aux dispositions du règlement général sur la protection des données (RGPD) et de la politique de confidentialité.
    
    <h2>Droits de Propriété Intellectuelle</h2>
    <p>Tous les contenus du Site, y compris mais sans s'y limiter, les textes, les images, les logos, les designs et les vidéos, sont la propriété de Symbolique Paris ou de tiers ayant autorisé Symbolique Paris à les utiliser. Toute reproduction, copie, modification ou utilisation non autorisée de ces contenus est strictement interdite.</p>
    
    <h2>Cookies :</h2>
    <p>Le Site peut utiliser des cookies pour améliorer l'expérience de l'utilisateur. Vous pouvez en savoir plus sur l'utilisation des cookies dans notre Politique de Confidentialité.</p>
    
    <h2>Liens Externes :</h2>
    <p>Le Site peut contenir des liens vers des sites web tiers. Symbolique Paris n'est pas responsable du contenu ou des pratiques de confidentialité de ces sites.</p>
    
    <h2>Responsabilité :</h2>
    <p>Symbolique Paris s'efforce de fournir des informations précises et à jour sur le Site, mais ne peut garantir l'exactitude, l'exhaustivité ou la pertinence de ces informations. L'utilisation du Site est à vos propres risques.</p>
    
    <h2>Contact :</h2>
    <div class="ml-infos">
        <p>Pour toute question ou préoccupation concernant le Site, veuillez nous contacter à l'adresse suivante :</p>
        <p>[Numéro de téléphone de contact]</p>
        <p>[Adresse e-mail de contact]</p>
    <p>
</div>