<div id="messagerie-admin-wrapper">    
    <h1>Messagerie</h1>
    
    <?php 
    
    if (!empty($messages)) {
    ?>
    <div id="table-message-wrapper">
        <table>
            <thead>
                <tr>
                    <th>email</th>
                    <th>Envoyé le</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
        <?php
            foreach ($messages as $message) {
                $user = User::findById($message->getIdUser());
                $email = User::findByEmail($message->getIdUser());
    
            if ($user) {
                $username = $user->getUsername();
                $email = $user->getEmail();
                } else {
                    $username = "Utilisateur supprimé";
                    $email = "X";
                }
        ?>
                <tr>
                    <td><?= $email ?></td>
                    <td><?= $message->getDate() ?></td>
                    <td id="message-text"><div id="div-td-message-username">Envoyé par <?= $username ?></div><?= $message->getText() ?></td>
                </tr>
        <?php
            }
        ?>
            </tbody>
        </table>
    </div>
    <?php
    }
    else {?>
        <p>Vous n'avez aucun message</p>
    <?php }
    ?>
    
    <a href="index.php?page=administration" class="admin-redirect">Retour à la page d'administration</a>
</div>