<h1>Messagerie</h1>

<?php 

if (!empty($messages)) {
?>
<table>
    <thead>
        <tr>
            <th>Utilisateur</th>
            <th>Message</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
<?php
    foreach ($messages as $message) {
?>
        <tr>
            <td><?= $message->getIdUser() ?></td>
            <td><?= $message->getDate() ?></td>
            <td><?= $message->getText() ?></td>
        </tr>
<?php
    }
?>
    </tbody>
</table>
<?php
}
else {
    return "Vous n'avez actuellement aucun message";
}
?>