<div id="privacy-policy-wrapper">    
    <h1>Politique de Confidentialité de Symbolique Paris</h1>
    
    <p>Date d'entrée en vigueur : 15 Août 2023</p>
    
    <p>Symbolique Paris ("nous", "notre", "nos") s'engage à protéger la confidentialité de vos informations personnelles. Cette politique de confidentialité vise à vous informer sur la manière dont nous collectons, utilisons, stockons et protégeons vos données personnelles lorsque vous utilisez notre site web ("le Site").</p>
    
    <h2>1. Informations Personnelles Collectées</h2>
    
    <p>1.1. Lors de votre inscription sur le Site, nous pouvons collecter les informations suivantes :</p>
    
    <ul class="pp-infos">
        <li>Votre nom complet</li>
        <li>Votre adresse e-mail</li>
        <li>Votre nom d'utilisateur</li>
        <li>Votre mot de passe (stocké de manière sécurisée)</li>
    </ul>
    
    <h2>2. Utilisation des Informations Personnelles</h2>
    
    <p>2.1. Nous utilisons les informations personnelles que vous nous fournissez aux fins suivantes :</p>
    
    <ul class="pp-infos">
        <li>Pour créer et gérer votre compte utilisateur.</li>
        <li>Pour vous permettre de vous connecter au Site.</li>
        <li>Pour vous envoyer des informations liées à votre compte et aux services que nous proposons.</li>
        <li>Pour répondre à vos questions et demandes d'assistance.</li>
        <li>Pour améliorer et personnaliser votre expérience sur le Site.</li>
    </ul>
    
    <h2>3. Protection des Données Personnelles</h2>
    
    <p>3.1. Nous mettons en place des mesures de sécurité techniques et organisationnelles appropriées pour protéger vos données personnelles contre tout accès non autorisé, perte, altération ou divulgation.</p>
    
    <p>3.2. Votre mot de passe est stocké de manière sécurisée sous forme hachée, ce qui signifie que même nous n'avons pas accès à votre mot de passe en clair.</p>
    
    <h2>4. Partage des Informations Personnelles</h2>
    
    <p>Nous ne partageons pas vos informations personnelles avec des tiers, sauf dans les cas suivants :</p>
    
    <ul class="pp-infos">
        <li>Lorsque cela est requis par la loi ou dans le cadre d'une procédure judiciaire.</li>
        <li>Pour répondre à des demandes légales émanant d'autorités compétentes.</li>
        <li>Pour protéger nos droits, notre confidentialité, notre sécurité ou notre propriété, ainsi que ceux de nos utilisateurs et du public.</li>
    </ul>
    
    <h2>5. Droits des Utilisateurs</h2>
    
    <p>Vous avez le droit de :</p>
    
    <ul class="pp-infos">
        <li>Accéder aux informations personnelles que nous détenons à votre sujet.</li>
        <li>Rectifier des données inexactes ou incomplètes.</li>
        <li>Supprimer vos données personnelles, dans la mesure où cela n'entre pas en conflit avec nos obligations légales de conservation.</li>
    </ul>
    
    <h2>6. Modifications de la Politique de Confidentialité</h2>
    
    <p>Nous nous réservons le droit de modifier cette politique de confidentialité à tout moment. Les modifications seront publiées sur le Site et prendront effet dès leur publication. Il vous incombe de vérifier régulièrement la politique de confidentialité pour vous tenir informé des changements.</p>
    
    <h2>7. Contact :</h2>
    
    <p>Si vous avez des questions ou des préoccupations concernant cette politique de confidentialité ou vos données personnelles, veuillez nous contacter à l'adresse suivante : symbolique_paris@yahoo.com.</p>
    
    <p id="thx-text">En utilisant le Site, vous acceptez les termes de cette politique de confidentialité. <br>Symbolique Paris vous remercie de votre confiance.</p>
</div>